#!/usr/bin/env ruby
require 'rubygems'
require File.dirname(__FILE__) + "/../../lib/cards" # you probably want to include the gem version
require 'cards/numbers_parser'
include Cards

# this requires numbers '09, before that you must export to csv and use the csv parser

def table(name)
  file = File.dirname(__FILE__) + "/Voting Example.numbers"
  NumbersParser.new(file, name)
end

CardWall.colors[:goal] = :green
CardWall.writer = GraffleWriter

CardWall.from table("Goals") do
  column :goal
end

CardWall.from table("Workflow") do
  row :role
  column :task, :wrap_at => 5
end

CardWall.from table("Stories") do
  row :activity
  row :task
  column :story, :wrap_at => 4 do |card, row|
    card.name = "                                       #{row[:estimate]}\n\n#{card.name}" unless row[:estimate].blank?
    card.name << "\n\n#{row[:note]}" unless row[:note].blank?    
  end
end
